# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  weight = 1
  identifier = "home"

[[main]]
  name = "About me"
  url = "#about"
  parent = "home"
  weight = 1

[[main]]
  name = "Publications"
  url = "#publications"
  parent = "home"
  weight = 2

[[main]]
  name = "Blog"
  url = "#posts"
  parent = "home"
  weight = 3

[[main]]
  name = "Talks"
  url = "#talks"
  parent = "home"
  weight = 4

[[main]]
  name = "Projects"
  url = "#projects"
  parent = "home"
  weight = 5

[[main]]
  name = "Activities"  # Title of the link.
  url = "activities/"  # Widget Page folder name.
  weight = 6  # Position of the link in the navigation bar.
  identifier = "activities"

[[main]]
  name = "CV"
  weight = 8
  identifier = "cv"

[[main]]
  name = "Short CV"
  url = "files/gabriele_sarti_cv.pdf"
  parent = "cv"
  weight = 1

[[main]]
  name = "Academic CV"
  url = "files/gabriele_sarti_academic_cv.pdf"
  parent = "cv"
  weight = 1

[[main]]
  name = "Communities"
  weight = 9
  identifier = "communities"

[[main]]
  name = "AI2S"
  url = "https://www.ai2s.it"
  parent = "communities"
  weight = 1

[[main]]
  name = "AISIG"
  url = "https://www.aisig.org"
  parent = "communities"
  weight = 2

# [[main]]
#   name = "Contact"
#   url = "#contact"
#   weight = 8

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 9
