# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 2

[[main]]
  name = "Blog"
  url = "#posts"
  weight = 3

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 4

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 5

[[main]]
  name = "Activities"  # Title of the link.
  url = "activities/"  # Widget Page folder name.
  weight = 6  # Position of the link in the navigation bar.
  identifier = "activities"

[[main]]
  name = "Teaching"
  url = "teaching/"
  weight = 7
  identifier = "teaching"

[[main]]
  name = "Curriculum"
  url = "files/cv.pdf"
  weight = 8

[[main]]
  name = "AI2S"
  url = "https://www.ai2s.it"
  weight = 9

# [[main]]
#   name = "Contact"
#   url = "#contact"
#   weight = 8

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 9
